- name: pull mini_project image
  hosts: all
  tasks:
    # - name: Start service
    #   service:
    #     name: docker
    #     state: started

    - name: Install pip requests library
      pip:
        name: requests
        state: present

    - name: stopping old container
      shell: docker ps -aq --filter ancestor="samaelarch/mini_project" | xargs -r docker stop

    - name: deleting old container
      shell: docker ps -aq --filter ancestor="samaelarch/mini_project" | xargs -r docker rm

    - name: remove old image
      shell: docker rmi samaelarch/mini_project

    - name: pull the image
      docker_image:
        name: samaelarch/mini_project
        source: pull

    - name: creating updated container
      shell: docker run -id --name calc samaelarch/mini_project
