- name: pull mini_project image
  hosts: all
  vars:
    pip_package_requirements:
      - "requests"
  tasks:
    # - name: Start service
    #   service:
    #     name: docker
    #     state: started

    - name: Install pip requests library
      pip:
        name: "{{ item }}"
        state: present
        with_items: "{{ pip_package_requirements }}"

    - name: pull the image
      docker_image:
        name: samaelarch/mini_project
        source: pull

    - name: stopping old container
      shell: docker ps -aq --filter ancestor="samaelarch/mini_project" | xargs -r docker stop

    - name: deleting old container
      shell: docker ps -aq --filter ancestor="samaelarch/mini_project" | xargs -r docker rm

    - name: creating updated container
      shell: docker run -it --name calc samaelarch/mini_project
